version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@3.4.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          context: orb-publishing
          filters: *filters
      - orb-tools/pack:
          context: orb-publishing
          filters: *filters
      - orb-tools/review:
          context: orb-publishing
          filters: *filters
      - shellcheck/check:
          context: orb-publishing
          filters: *filters
      - orb-tools/publish:
          orb_name: nexbus/graphql-federation
          vcs_type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          orb_name: nexbus/graphql-federation
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
